osc="no"
border="no"

hwdec="auto-copy"
gpu-api="vulkan"
profile="gpu-hq"
vo="gpu-next"

volume=100
volume-max=100

sub-border-size=1
sub-color="#FFD575"
sub-font="Jost*"
sub-font-size=48
sub-shadow-color="#000000"
sub-shadow-offset=2
