name: Build packages

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = partio.cachix.org-1:W8w3kE6/UOLs0dg1kxCDYvllNVsaBFbNBofVR+wYhrw= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://partio.cachix.org https://cache.nixos.org/

      - name: Install cachix
        uses: cachix/cachix-action@v16
        with:
          name: partio
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # https://git.lix.systems/lix-project/lix/issues/545#issuecomment-8412
      - name: Fixes and hacks
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Build all packages
        run: nix-shell -p just --run "just build"
