name: Create install ISO

on:
  schedule:
    - cron: '0 0 1 */2 *'
  workflow_dispatch:
  pull_request:
    paths:
      - 'iso/**'

permissions:
  contents: write

jobs:
  iso:
    name: Create install ISO
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-codeql: true
          remove-haskell: true
          remove-docker-images: true

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = partio.cachix.org-1:W8w3kE6/UOLs0dg1kxCDYvllNVsaBFbNBofVR+wYhrw= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://partio.cachix.org https://cache.nixos.org/

      - name: Install cachix
        uses: cachix/cachix-action@v16
        with:
          name: partio
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # https://git.lix.systems/lix-project/lix/issues/545#issuecomment-8412
      - name: Fixes and hacks
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Build iso
        run: nix-shell -p just --run "just create"

      - name: Make release
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          today=$(date +'%Y-%m-%d')
          gh release create "$today" --title "$today" --notes ""
          gh release upload "$today" ./result/iso/*.iso
