name: Update npins

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 4" # runs weekly on thursday at 02:00 UTC

jobs:
  update-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update npins
        run: |
          nix-shell -p npins --run "npins upgrade"
          nix-shell -p npins --run "npins update"
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(deps): update lockfiles"
