name: Update npins

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 4" # runs weekly on thursday at 02:00 UTC

jobs:
  update-npins:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pr-url: ${{ steps.pr.outputs.pull-request-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update npins
        run: |
          nix-shell -p npins --run "npins upgrade"
          nix-shell -p npins --run "npins update" > update.log 2>&1

      - name: Prepare PR body with code block
        run: |
          echo '```' > pr_body.md
          cat update.log >> pr_body.md
          echo '```' >> pr_body.md

      - name: Create Pull request
        uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          title: "chore: update npins"
          commit-message: "chore: update npins"
          body-path: pr_body.md
          branch: update-npins

  build:
    runs-on: ubuntu-latest
    needs: update-npins
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = partio.cachix.org-1:W8w3kE6/UOLs0dg1kxCDYvllNVsaBFbNBofVR+wYhrw= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://partio.cachix.org https://cache.nixos.org/

      - name: Install cachix
        uses: cachix/cachix-action@v16
        with:
          name: partio
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build all packages
        run: nix-shell -p just --run "just build"

      - name: Merge Pull Request
        run: gh pr merge --merge --auto --delete-branch "${{ needs.update-npins.outputs.pr-url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
