name: Update npins

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 4" # runs weekly on thursday at 02:00 UTC

jobs:
  update-npins:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pr-url: ${{ steps.pr.outputs.pull-request-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update npins
        run: |
          nix-shell -p npins --run "npins upgrade"
          nix-shell -p npins --run "npins update"

      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create Pull request
        uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          title: "chore: update npins"
          commit-message: "chore: update npins"
          body: "Automated `npins` update."
          branch: update-npins
          token: ${{ steps.generate-token.outputs.token }}
